apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      # imagePullSecrets:
      # - name: my-registry-key
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6359
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6359
    targetPort: 6359