apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      # imagePullSecrets:
      # - name: my-registry-key
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
          # env:
          # {{- range .Values.containerEnvVars}}
          # - name: {{ .name }}
          #   value: {{ .value | quote }}
          # {{- end}}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017